# Generated by Django 6.0.3 on 2026-03-13 09:05

import importorder.services.generate_importoder_code
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importorder', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='code',
            field=models.CharField(default=importorder.services.generate_importoder_code.generate_importoder_code, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='import/invoices/'),
        ),
        migrations.AlterField(
            model_name='importorder',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
