# Generated by Django 6.0.3 on 2026-03-25 10:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exportorder', '0001_initial'),
        ('product', '0001_initial'),
        ('productwarehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exportorder.exportorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productwarehouse.productwarehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['export_order'], name='exportorder_export__b43bc3_idx')],
            },
        ),
    ]
