# Generated by Django 6.0.3 on 2026-03-18 08:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportorder', '0002_initial'),
        ('exportorderitem', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportorderitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='exportorderitem',
            name='export_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exportorder.exportorder'),
        ),
        migrations.AlterField(
            model_name='exportorderitem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='exportorderitem',
            index=models.Index(fields=['export_order'], name='exportorder_export__b43bc3_idx'),
        ),
    ]
