# Generated by Django 6.0.3 on 2026-03-18 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importorder', '0003_importorder_total_amount_alter_importorder_code_and_more'),
        ('importorderitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importorderitem',
            name='import_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='importorder.importorder'),
        ),
        migrations.AlterField(
            model_name='importorderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
